[package]
name = "smiles_parser"
version = "0.1.0"
authors = ["Einar Kjellback <einarkjellback@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]